# https://nikitabobko.github.io/AeroSpace/guide#config-samples

config-version = 2

start-at-login = true
automatically-unhide-macos-hidden-apps = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
persistent-workspaces = ['ARCM', 'GHOSTTY', 'ARCD', 'CHROME', 'FINDER', 'EMPTY', 'DOCKER']

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    equal = 'balance-sizes'
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace ARCM'

    alt-2 = 'workspace GHOSTTY'
    alt-backtick = 'workspace GHOSTTY'

    alt-3 = 'workspace ARCD'
    alt-4 = 'workspace CHROME'

    alt-f = 'workspace FINDER'
    alt-o = 'workspace OBSIDIAN'
    alt-e = 'workspace EMPTY' 
    alt-d = 'workspace DOCKER' 
    alt-n = 'workspace NORD' 

    alt-ctrl-h = 'workspace prev' 
    alt-ctrl-l = 'workspace next' 

    alt-shift-1 = ['move-node-to-workspace ARCM', 'workspace ARCM'] 
    alt-shift-2 = ['move-node-to-workspace GHOSTTY', 'workspace GHOSTTY'] 
    alt-shift-3 = ['move-node-to-workspace ARCD', 'workspace ARCD'] 
    alt-shift-4 = ['move-node-to-workspace CHROME', 'workspace CHROME'] 
    alt-shift-e = ['move-node-to-workspace EMPTY', 'workspace EMPTY']

    alt-sectionSign = 'workspace-back-and-forth'
    alt-shift-m = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    r = ['reload-config', 'mode main']
    esc = ['mode main']
    space = ['layout floating tiling', 'mode main']

[[on-window-detected]]
    if.app-id = 'company.thebrowser.Browser'
    run = 'move-node-to-workspace ARCM' 

[[on-window-detected]]
    if.app-id = 'com.mitchellh.ghostty'
    run = ['layout tiling', 'move-node-to-workspace GHOSTTY'] 

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = ['layout floating', 'move-node-to-workspace FINDER']

[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace CHROME' 

[[on-window-detected]]
    if.app-id = 'ru.keepcoder.Telegram'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'notion.id'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.figma.Desktop'
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.hnc.Discord'
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.electron.dockerdesktop'
    run = ['layout floating', 'move-node-to-workspace DOCKER'] 

[[on-window-detected]]
    if.app-id = 'com.apple.iCal'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.apple.AppStore'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.apple.ScreenContinuity'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.apple.iBooksX'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.microsoft.VSCode'
    run = ['layout floating'] 

[[on-window-detected]]
    if.app-id = 'com.nordvpn.NordVPN'
    run = ['move-node-to-workspace NORD'] 

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = ['layout floating','move-node-to-workspace OBSIDIAN'] 
